# Generated by Django 3.0.5 on 2020-11-21 05:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0003_auto_20201121_1200'),
    ]

    operations = [
        migrations.RenameField(
            model_name='counter',
            old_name='id',
            new_name='_id',
        ),
    ]
