# Generated by Django 3.0.5 on 2020-11-21 05:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0004_auto_20201121_1218'),
    ]

    operations = [
        migrations.RenameField(
            model_name='counter',
            old_name='_id',
            new_name='id',
        ),
    ]
